
service: service-2-serverless-isragram-ts
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript

functions:
  hello:
    handler: handler.hello
